import { MusicianProfile, Instrument, MusicalStyle, JamSession } from '@/types';
import { BARCELONA_ZONES } from './zones';

export const SAMPLE_INSTRUMENTS: Instrument[] = [
  { id: 'inst-guitarra-acustica', name: 'Guitarra Acústica', category: 'cuerda' },
  { id: 'inst-guitarra-electrica', name: 'Guitarra Eléctrica', category: 'cuerda' },
  { id: 'inst-bajo', name: 'Bajo Eléctrico', category: 'cuerda' },
  { id: 'inst-bateria', name: 'Batería / Percusión', category: 'percusion' },
  { id: 'inst-piano', name: 'Piano / Teclado', category: 'teclado' },
  { id: 'inst-voz', name: 'Voz / Canto', category: 'voz' },
  { id: 'inst-saxofon', name: 'Saxofón', category: 'viento' },
  { id: 'inst-trompeta', name: 'Trompeta', category: 'viento' },
  { id: 'inst-violin', name: 'Violín', category: 'cuerda' },
  { id: 'inst-ukulele', name: 'Ukelele', category: 'cuerda' },
  { id: 'inst-cajon', name: 'Cajón Flamenco / Percusión', category: 'percusion' },
  { id: 'inst-sintetizador', name: 'Sintetizador', category: 'electronica' },
];

export const SAMPLE_STYLES: MusicalStyle[] = [
  { id: 'st-rock', name: 'Rock' },
  { id: 'st-pop', name: 'Pop' },
  { id: 'st-blues', name: 'Blues' },
  { id: 'st-jazz', name: 'Jazz' },
  { id: 'st-indie', name: 'Indie / Alt' },
  { id: 'st-rb', name: 'R&B / Soul' },
  { id: 'st-reggae', name: 'Reggae' },
  { id: 'st-flamenco', name: 'Flamenco / Fusión' },
  { id: 'st-funk', name: 'Funk' },
  { id: 'st-folk', name: 'Folk / Acústico' },
  { id: 'st-bossa', name: 'Bossa Nova' },
  { id: 'st-metal', name: 'Heavy Metal' },
];

export const SAMPLE_MUSICIAN_PROFILES: MusicianProfile[] = [
  {
    id: 'mus-1',
    username: 'marcdiaz_guitar',
    display_name: 'Marc Díaz',
    bio: 'Toco la guitarra rítmica desde hace 3 años. Me encanta improvisar blues y rock clásico los fines de semana sin pretensiones.',
    zone_id: 'z-gracia',
    zone: BARCELONA_ZONES[0],
    max_travel_km: 3,
    looking_for: 'Busco cantante o teclista para hacer jam acústica en parkings o locales de Gràcia.',
    is_currently_available: true,
    availability_updated_at: new Date().toISOString(),
    instruments: [SAMPLE_INSTRUMENTS[0], SAMPLE_INSTRUMENTS[1]],
    styles: [SAMPLE_STYLES[0], SAMPLE_STYLES[2], SAMPLE_STYLES[9]],
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    video_duration_seconds: 45,
    created_at: '2026-08-15T12:00:00Z',
  },
  {
    id: 'mus-2',
    username: 'laurabass_bcn',
    display_name: 'Laura Soler',
    bio: 'Bajista aficionada. Llevo 1 año aprendiendo bajo rítmico. Busco gente paciente para practicar el tempo y groove juntos.',
    zone_id: 'z-poblenou',
    zone: BARCELONA_ZONES[1],
    max_travel_km: 5,
    looking_for: 'Batería y guitarra para montar quedadas mensuales relajadas.',
    is_currently_available: true,
    availability_updated_at: new Date().toISOString(),
    instruments: [SAMPLE_INSTRUMENTS[2]],
    styles: [SAMPLE_STYLES[5], SAMPLE_STYLES[8], SAMPLE_STYLES[1]],
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    video_duration_seconds: 60,
    created_at: '2026-08-18T14:30:00Z',
  },
  {
    id: 'mus-3',
    username: 'pablo_drums',
    display_name: 'Pablo Ruiz',
    bio: 'Tengo batería electrónica en casa y caja de ritmos. Me adapto a casi todo: indie, rock, pop o reggae.',
    zone_id: 'z-eix-esq',
    zone: BARCELONA_ZONES[2],
    max_travel_km: 4,
    looking_for: 'Cualquier instrumentista que quiera hacer sesiones en mi estudio casero o bucle de ensayo.',
    is_currently_available: false,
    instruments: [SAMPLE_INSTRUMENTS[3], SAMPLE_INSTRUMENTS[10]],
    styles: [SAMPLE_STYLES[0], SAMPLE_STYLES[4], SAMPLE_STYLES[6]],
    created_at: '2026-08-20T09:15:00Z',
  },
  {
    id: 'mus-4',
    username: 'elena_keys',
    display_name: 'Elena Vidal',
    bio: 'Pianista aficionada desde niña. Me apasiona el jazz moderno, bossa nova y arreglos de música soul.',
    zone_id: 'z-born',
    zone: BARCELONA_ZONES[6],
    max_travel_km: 2,
    looking_for: 'Vocalista o saxofonista para temas tranquilos y bossas.',
    is_currently_available: true,
    availability_updated_at: new Date().toISOString(),
    instruments: [SAMPLE_INSTRUMENTS[4]],
    styles: [SAMPLE_STYLES[3], SAMPLE_STYLES[10], SAMPLE_STYLES[5]],
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    video_duration_seconds: 90,
    created_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'mus-5',
    username: 'carlos_sax',
    display_name: 'Carlos Mendoza',
    bio: 'Aprendiz entusiasta de saxofón alto. Disfruto improvisar escalas sobre bases de funk y blues.',
    zone_id: 'z-sants',
    zone: BARCELONA_ZONES[5],
    max_travel_km: 5,
    looking_for: 'Banda aficionada de funk/soul o guitarrista para tocar en parque/estudio.',
    is_currently_available: false,
    instruments: [SAMPLE_INSTRUMENTS[6]],
    styles: [SAMPLE_STYLES[8], SAMPLE_STYLES[2], SAMPLE_STYLES[3]],
    created_at: '2026-08-25T11:00:00Z',
  },
];

export const SAMPLE_JAMS: JamSession[] = [
  {
    id: 'jam-1',
    creator_id: 'mus-1',
    creator: SAMPLE_MUSICIAN_PROFILES[0],
    title: 'Jam Acústica Rock & Blues de fin de semana',
    description: 'Buscamos 2 o 3 personas (bajo, teclado o voz) para reunirnos este sábado por la tarde y repasar acordes sencillos y jams de rock clásico. Ambiente 100% amigable y sin presiones.',
    zone_id: 'z-gracia',
    zone: BARCELONA_ZONES[0],
    event_date: '2026-09-05T17:00:00Z',
    max_capacity: 4,
    current_participants_count: 2,
    status: 'abierta',
    created_at: '2026-08-28T10:00:00Z',
  },
  {
    id: 'jam-2',
    creator_id: 'mus-4',
    creator: SAMPLE_MUSICIAN_PROFILES[3],
    title: 'Sesión Bossa Nova & Jazz estándar en Poblenou',
    description: 'Quedada en local de ensayo para repasar temas de Tom Jobim, Miles Davis y estandars clásicos. Se busca voz femenina/masculina y percusión suave.',
    zone_id: 'z-poblenou',
    zone: BARCELONA_ZONES[1],
    event_date: '2026-09-06T18:30:00Z',
    max_capacity: 5,
    current_participants_count: 3,
    status: 'abierta',
    created_at: '2026-08-27T16:20:00Z',
  },
];
